packages:
  - "apps/*"
  - "packages/*"

catalog:
  "ai": "^5.0.59"
  "@ai-sdk/anthropic": "^2.0.23"
  "@ai-sdk/google": "^2.0.17"
  "@ai-sdk/openai": "^2.0.42"
  "@temporalio/common": "^1.13.0"
  "@temporalio/proto": "^1.13.0"
  "@temporalio/client": "^1.13.0"
  "@temporalio/worker": "^1.13.0"
  "@temporalio/activity": "^1.13.0"
  "@temporalio/workflow": "^1.13.0"
  "@temporalio/interceptors-opentelemetry": "^1.13.0"
  "@rocicorp/zero": "^0.23.2025090100"
  "@opentelemetry/api": "^1.9.0"
  "eslint": "^9.33.0"
  "tsup": "^8.4.0"
  "typescript": "^5.6.3"
  "zod": "^4.1.11"
  "zero-svelte": "^0.8.1"
