packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@temporalio/common": "^1.13.0"
  "@temporalio/proto": "^1.13.0"
  "@temporalio/client": "^1.13.0"
  "@temporalio/worker": "^1.13.0"
  "@temporalio/activity": "^1.13.0"
  "@temporalio/workflow": "^1.13.0"
  "@temporalio/interceptors-opentelemetry": "^1.13.0"
  "@rocicorp/zero": "^0.23.2025090100"
