packages:
  - "apps/*"
  - "packages/*"

catalog:
  "svelte": "^5.38.6"
  "@sveltejs/kit": "^2.37.0"
  "@sveltejs/vite-plugin-svelte": "^6.1.3"
  "svelte-check": "^4.2.1"
  "svelte-sonner": "^1.0.5"
  bits-ui: "^2.8.10"
  clsx: "^2.1.1"
  eslint: "^9.18.0"
  mode-watcher: "^1.0.8"
  prettier: "^3.4.2"
  tailwindcss: "^4.0.0"
  tailwind-merge: "^3.3.1"
  tailwind-variants: "^1.0.0"
  "@types/node": "^24.3.0"
  "@tanstack/svelte-table": "9.0.0-alpha.10"
  "@temporalio/common": "^1.13.0"
  "@temporalio/proto": "^1.13.0"
  "@temporalio/client": "^1.13.0"
  "@temporalio/worker": "^1.13.0"
  "@temporalio/activity": "^1.13.0"
  "@temporalio/workflow": "^1.13.0"
  "@temporalio/interceptors-opentelemetry": "^1.13.0"
  "@rocicorp/zero": "^0.23.2025090100"
