// Generated by Gemini
import * as schema from './schema';
import { InferSelectModel } from 'drizzle-orm';

export type Message = InferSelectModel<typeof schema.MessageSchema>;
export type Tool = InferSelectModel<typeof schema.ToolSchema>;
export type Conversation = InferSelectModel<typeof schema.ConversationSchema>;